"global":
  "resolve_timeout": "5m"
"receivers":
- "name": "null"
- "name": "webhook"
  "webhook_configs":
  - "send_resolved": true
    "http_config": {}
    "url": "http://webhook.default.svc.cluster.local:8080/webhook"
"route":
  "receiver": "null"
  "group_by":
  - "alertname"
  "group_interval": "10s"
  "group_wait": "10s"
  "repeat_interval": "1h"
  "routes":
  - "match":
      "alertname": "ClusterWarning"
    "receiver": "webhook"
