apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: webhook
  name: webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webhook
  template:
    metadata:
      creationTimestamp: null
      labels:
         name: webhook
    spec:
      containers:
      - image: webhook:1.0
        imagePullPolicy: IfNotPresent
        name: webhook
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: default
spec:
  selector:
    name: webhook
  type: ClusterIP
  ports:
  - port: 8080

